twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        turnstile_site_key: '%env(TURNSTILE_SITE_KEY)%'

when@test:
    twig:
        strict_variables: true
